// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ascii_
Rcpp::IntegerMatrix ascii_(std::string filename, unsigned int width, unsigned int height, int verbosity);
RcppExport SEXP _devout_ascii_(SEXP filenameSEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    rcpp_result_gen = Rcpp::wrap(ascii_(filename, width, height, verbosity));
    return rcpp_result_gen;
END_RCPP
}
// descriptive_
bool descriptive_(int verbosity, int width, int height);
RcppExport SEXP _devout_descriptive_(SEXP verbositySEXP, SEXP widthSEXP, SEXP heightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type verbosity(verbositySEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    rcpp_result_gen = Rcpp::wrap(descriptive_(verbosity, width, height));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_devout_ascii_", (DL_FUNC) &_devout_ascii_, 4},
    {"_devout_descriptive_", (DL_FUNC) &_devout_descriptive_, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_devout(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
