# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create an ascii graphics device
#'
#' @param filename if given, write ascii to this file, otherwise write to console
#' @param width,height dimensions of text output (in characters)
#' @param verbosity level. default: 0
#'
ascii_ <- function(filename, width, height, verbosity = 0L) {
    .Call(`_devout_ascii_`, filename, width, height, verbosity)
}

#' Create a descriptive graphics device
#'
#' @param verbosity level. default: 1
#' @param width,height nominal size of drawing area in pixels.
#'
descriptive_ <- function(verbosity = 1L, width = 400L, height = 300L) {
    .Call(`_devout_descriptive_`, verbosity, width, height)
}

