# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a rdevice graphics device
#'
#' @param rfunction name of callback function
#' @param rdata a list of information used on the R side
#'
rdevice_ <- function(rfunction, rdata) {
    .Call(`_devout_rdevice_`, rfunction, rdata)
}

