# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a rdevice graphics device
#'
#' @param rdata a list of information used on the R side
#' @param device_name name for this device
#'
rdevice_ <- function(rdata, device_name) {
    .Call(`_devout_rdevice_`, rdata, device_name)
}

